name: test
on:
  push:
    branches-ignore:
      - main
  workflow_call:
permissions:
  id-token: write
  contents: read
  pull-requests: write
  checks: write
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      bozupy: ${{ steps.filter.outputs.bozupy }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            bozupy:
              - 'bozupy/**'
              - 'uv.lock'
              - 'pyproject.toml'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          takumi_guard_pypi_bot_id: ${{ secrets.TAKUMI_GUARD_PYPI_BOT_ID }}
      - name: Run flake8
        run: |
          uv run flake8 ./bozupy ./tests
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          takumi_guard_pypi_bot_id: ${{ secrets.TAKUMI_GUARD_PYPI_BOT_ID }}
      - name: run mypy
        run: |
           uv run mypy ./bozupy ./tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          takumi_guard_pypi_bot_id: ${{ secrets.TAKUMI_GUARD_PYPI_BOT_ID }}
      - name: create results directory
        run: |
          mkdir -p /tmp/results
      - name: run pytest
        run: |
          uv run python3 -m pytest --junit-xml /tmp/results/pytest.xml -v --cov=bozupy --cov-report=term-missing
        continue-on-error: true
      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: test_results
          path: /tmp/results/*.xml
      - name: publish test results
        uses: mikepenz/action-junit-report@5e05ac00ad0604dfb7e313ae412aa3284f4906d6 # v6.3.0
        if: always()
        with:
          report_paths: /tmp/results/*.xml
          check_name: Pytest Report
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          takumi_guard_pypi_bot_id: ${{ secrets.TAKUMI_GUARD_PYPI_BOT_ID }}
      - name: check coverage
        run: |
          result=$(uv run python3 -m pytest --cov=bozupy | grep "TOTAL.*%")
          percent="$(echo ${result} | cut -d" " -f 4 | sed -e "s/%//g")"
          if [ "${percent}" -lt 85 ]; then
              echo "Coverage is less than 85%."
              exit 1
          fi
  version-match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: get pyproject.toml version
        id: get-pyproject-version
        uses: ./.github/actions/get-version
      - name: get setting.py version
        id: get-setting-version
        run: |
          SETTING_VERSION=$(grep "BOZUPY_VERSION: str = " bozupy/setting.py | sed -e "s/.* \"//" | sed -e "s/\".*//")
          echo "version=${SETTING_VERSION}" >> "${GITHUB_OUTPUT}"
      - name: check version match
        run: |
          if [ "${{ steps.get-pyproject-version.outputs.version }}" != "${{ steps.get-setting-version.outputs.version }}" ]; then
              echo "BOZUPY_VERSION and pyproject.toml version are different."
              exit 1
          fi
  version-bump:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ (needs.changes.outputs.bozupy == 'true') && (github.event_name == 'pull_request') }}
    steps:
      - uses: actions/checkout@v6
      - name: new branch version
        uses: ./.github/actions/get-version
        id: new-version
      - name: main branch version
        id: old-version
        uses: ./.github/actions/get-version
        with:
          branch: main
      - name: check version between main and new branch
        run: |
          if [ "${{ steps.new-version.outputs.version }}" = "${{ steps.old-version.outputs.version }}" ]; then
              echo ".version is not bumped yet."
              exit 1
          fi
  check-code:
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.bozupy == 'true'
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          takumi_guard_pypi_bot_id: ${{ secrets.TAKUMI_GUARD_PYPI_BOT_ID }}
      - name: code check
        run: |
          uv run python3 bin/code-check.py
